apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: awx-projects-claim
  namespace: awx
spec:
  storageClassName: standard
  volumeName: local-pv-claim
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
