---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
  namespace: awx
spec:
  service_type: nodeport
  hostname: awxprod.lottomatica.com
  extra_settings:
    - setting: CSRF_TRUSTED_ORIGINS
      value:
        - "https://awxprod.lottomatica.com"
  postgres_configuration_secret: awx-postgres-configuration
#  postgres_storage_class: standard
  projects_persistence: true
  projects_storage_access_mode: ReadWriteOnce
  web_extra_volume_mounts: |
    - name: static-data
      mountPath: /var/lib/projects
  extra_volumes: |
    - name: static-data
      persistentVolumeClaim:
        claimName:  awx-static-data-pvc
