apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv-postgresql
  namespace: awx
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: standard
  local:
    path: /mnt/data/local-storage-pv-postgresql
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/awx-pvc
          operator: In
          values:
          - yep
