apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-13-awx-postgres-13-0
  namespace: awx
spec:
  storageClassName: standard
  volumeName: local-pv-postgresql
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
