apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Values.namespace }}
  name: "ado-agent-configs"
  labels:
    {{- include "ado-agent.labels" . | nindent 4 }}
data:
  TARGETARCH: {{ .Values.env.configs.TARGETARCH }}
