apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Values.namespace }}
  name: "ado-agent-creds"
  labels:
    {{- include "ado-agent.labels" . | nindent 4 }}
type: Opaque
data:
  ADO_URL: {{ "fake_value" | b64enc }} # TODO: to pass at deploy time
  ADO_TOKEN: {{ "fake_value" | b64enc }} # TODO: to pass at deploy time
  ADO_POOL: {{ "fake_value" | b64enc }} # TODO: to pass at deploy time
