apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Values.namespace }}
  name: "ado-agent-creds"
  labels:
    {{- include "ado-agent.labels" . | nindent 4 }}
type: Opaque
data:
  ADO_URL: {{ .Values.env.secrets.ADO_URL | b64enc }}
  ADO_TOKEN: {{ .Values.env.secrets.ADO_TOKEN | b64enc }}
  ADO_POOL: {{ .Values.env.secrets.ADO_POOL | b64enc }}
