name: Test Workflow - Job Artifact
on:
  push:
    branches:
      - "master"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build test.txt file
        run: |
          echo "Test 1" > test.txt
          cat test.txt
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: test.txt
          path: test.txt
  download_artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: test.txt
      - name: Read test.txt file
        run: cat test.txt