name: Test Workflow - Cache
on:
  push:
    branches:
      - "master"
    paths:
      - ".github/workflow/test-wf-cache.yml"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: List
        run: ls
      - name: Build test.txt file
        run: |
          echo "Test 1" > test.txt
          cat test.txt
      - name: Cache
        uses: actions/cache@v4
        with:
          path: test.txt
          key: test-depends-${{ hashFiles('test.txt') }}